version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: null

formats: []

# Cấu hình để nó đọc file index.html của bạn
# Nếu bạn dùng định dạng đơn giản, RTD sẽ tự nhận diện.
